name: CI

on:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches: [ "main" ]

jobs:
  build:
    env:
      TAGS: "with_gvisor,with_quic,with_wireguard,with_utls,with_reality_server,with_clash_api"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: SagerNet/sing-box
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      
      - name: Build sing-box
        run: |
          make TAGS=$TAGS
          echo 'VERSION<<EOF' >> $GITHUB_ENV
          ./sing-box version >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: sing-box
          body: ${{ env.VERSION }}
          overwrite: true
