name: CI

on:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches: [ "main" ]
  watch:
    types: [started]

jobs:
  build:
    env:
      TAGS: "with_quic,with_grpc,with_wireguard,with_utls"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: SagerNet/sing-box
          fetch-depth: 0
      - run: git checkout $(git describe --tags --abbrev=0)

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      
      - name: Build sing-box
        run: |
          CGO_ENABLED=0 make TAGS=$TAGS
          echo 'VERSION<<EOF' >> $GITHUB_ENV
          ./sing-box version >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Delete older Releases
        uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          keep_latest: 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          file: sing-box
          body: ${{ env.VERSION }}
